#!/bin/bash

set -ue

if [ "$#" -ne "1" ]; then
    echo "usage: $0 <concourse-build-url>" >&2
    exit 1
fi

# url like https://garden.ci.cf-app.com/teams/main/pipelines/main/jobs/guardian-nerdful/builds/68

fly -t garden-ci w --url "$1" | less -S -R
