---
- hosts: all
  tags: [macos]
  tasks:
  - name: update brew
    homebrew: update_homebrew=yes

  - name: add Homebrew taps
    homebrew_tap: name={{item}}
    with_items:
    - homebrew/cask-fonts
    - cloudfoundry/tap
    - git-duet/tap
    - neovim/neovim

  - name: unlink terraform
    command: brew unlink terraform

  - name: install Homebrew packages
    homebrew:
      name:
      - ack
      - ag
      - awscli
      - bash
      - bash-completion@2
      - bosh-cli
      - cf-cli
      - chruby
      - coreutils
      - ctags
      - curl
      - direnv
      - docker
      - docker-machine
      - fasd
      - fortune
      - fzf
      - git
      - git-duet
      - go
      - htop
      - jq
      - jsonpp
      - lastpass-cli
      - libgit2
      - kubectl
      - neovim
      - npm
      - pstree
      - python3
      - python@2
      - reattach-to-user-namespace
      - ripgrep
      - ruby-install
      - shellcheck
      - ssh-copy-id
      - sshuttle
      - tfenv
      - tig
      - tmate
      - tmux
      - tree
      - vim
      - watch
      - wget
      - yarn
      state: latest

  - name: install Homebrew casks
    homebrew_cask: name={{item}} install_options=appdir=/Applications
    with_items:
    - docker
    - flycut
    - font-inconsolata
    - font-inconsolata-nerd-font
    - google-cloud-sdk
    - iterm2
    - shiftit
    - vagrant
    - virtualbox
    - ngrok

  - name: install neovim pip package
    pip: name=neovim state=latest

  - name: install neovim pip3 package
    pip: name=neovim state=latest executable=/usr/local/bin/pip3

  - name: install terraform 0.12.18
    command: tfenv install 0.12.18

  - name: use terraform 0.12.18
    command: tfenv use 0.12.18
