---
- hosts: all
  tags: [macos]
  tasks:
  - name: update brew
    homebrew: update_homebrew=yes

  - name: add Homebrew taps
    homebrew_tap: name={{item}}
    with_items:
    - homebrew/cask-fonts
    - cloudfoundry/tap
    - git-duet/tap
    - neovim/neovim

  - name: unlink terraform
    shell: brew unlink terraform || true

  - name: install Homebrew packages
    homebrew:
      name:
      - ack
      - ag
      - awscli
      - bash
      - bash-completion@2
      - bosh-cli
      - cf-cli
      - chruby
      - coreutils
      - ctags
      - curl
      - direnv
      - docker
      - docker-machine
      - fasd
      - fortune
      - fzf
      - git
      - git-duet
      - go
      - htop
      - jq
      - jsonpp
      - lastpass-cli
      - libgit2
      - kubectl
      - neovim
      - npm
      - pstree
      - python3
      - python@2
      - reattach-to-user-namespace
      - ripgrep
      - ruby-install
      - shellcheck
      - ssh-copy-id
      - sshuttle
      - tfenv
      - tig
      - tmate
      - tmux
      - tree
      - vim
      - watch
      - wget
      - yarn
      state: latest

  - name: install Homebrew casks
    homebrew_cask: name={{item}} install_options=appdir=/Applications
    with_items:
    - docker
    - flycut
    - font-inconsolata
    - font-inconsolata-nerd-font
    - google-cloud-sdk
    - iterm2
    - shiftit
    - vagrant
    - ngrok

  - name: get virtualbox version
    command: VBoxManage -v
    register: vbox_version
    failed_when: vbox_version.rc != 0 and vbox_version.rc != 2

  - name: uninstall virtualbox if not 6.0
    homebrew_cask:
      name: virtualbox
      state: absent
    when: vbox_version.rc == 0 and not vbox_version.stdout.startswith("6.0.")

  - name: install virtualbox 6.0
    command: brew cask install https://raw.githubusercontent.com/caskroom/homebrew-cask/91241febe442803aa2e645acfbebda374a23a1ea/Casks/virtualbox.rb
    when: vbox_version.rc == 2 or not vbox_version.stdout.startswith("6.0.")

  - name: install neovim pip package
    pip: name=neovim state=latest

  - name: install neovim pip3 package
    pip: name=neovim state=latest executable=/usr/local/bin/pip3

  - name: pin terraform 0.12.19
    shell: tfenv install 0.12.19 && tfenv use 0.12.19
